config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  post 'calculate_stardate', to: 'pages#calculate_stardate'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
require 'date'

class PagesController < ApplicationController
  def home
  end

  def calculate_stardate
    @stardate = date_to_stardate(params[:date])
  end

  private

  def date_to_stardate(date)
    @date = params[:date].to_date
    @stardate_year_month = ("#{@date.year - 1900}#{('%02i' % @date.month)}").to_i
    # @stardate_month = ('%02i' % @date.month)
    @stardate_day = @date.day
    # raise
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: [
          turbo_stream.replace("result_frame", partial: "pages/result", locals: { stardate: @stardate }),
          turbo_stream.replace("form_frame", partial: "pages/recalculate_button")
        ]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DateToStardate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Monofett&family=Orbitron:wght@400..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_with url: calculate_stardate_path, method: :post, data: { turbo_frame: 'form_frame' } do |form| %>
  <div class="form-group">
    <%= form.date_field :date, class: "form-control", placeholder: "Select a date", data: { controller: "datepicker" } %>
  </div>
  <div class="form-group text-center">
    <%= form.submit "Calculate", class: "btn btn-primary trek-button" %>
  </div>
<% end %>

app/views/pages/_recalculate_button.html.erb
<%#= button_to "Recalculate", root_path, method: :get, class: "btn btn-secondary", data: { turbo_frame: "form_frame" } %>

app/views/pages/_result.html.erb
<div class="text-center">
  <h2>Your Stardate</h2>
  <div class="d-flex animated-number-container">
    <div
      data-controller="animated-number"
      data-animated-number-start-value="<%= @stardate_year_month - 100 %>"
      data-animated-number-end-value="<%= @stardate_year_month %>"
      data-animated-number-duration-value="2000"
    ></div>
    <div>.</div>
    <% if @stardate_day.digits.length == 2 %>
      <div
          data-controller="animated-number"
          data-animated-number-start-value="00"
          data-animated-number-end-value="<%= @stardate_day %>"
          data-animated-number-duration-value="2000"
        ></div>
      </div>
    <% else %>
      <div><%= '%02i' % @stardate_day %></div>
    <% end %>
  </div>

  <%= button_to "Recalculate", root_path, method: :get, class: "btn btn-primary trek-button", data: { turbo_frame: "form_frame" } %>
</div>

app/views/pages/home.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-12 col-md-8 col-lg-6">
      <h1 class="text-center">Stardate Calculator</h1>

      <%= turbo_frame_tag "form_frame" do %>
        <%= render 'form' %>
      <% end %>

      <%= turbo_frame_tag "result_frame" do %>
        <!-- Result will be rendered here -->
      <% end %>
    </div>
  </div>
</div>